config/routes.rb
Rails.application.routes.draw do
  resources :pups

  devise_for :users
  root "pups#index"
  get "about" => "pages#about" #creates about_path

end

app/models/pup.rb
class Pup < ActiveRecord::Base
	belongs_to :user
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]

  validates :image, presence: true
  
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :pups, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

 # protect url
 USERS = { ENV['PUPPERESTING_USER'] => ENV['PUPPERESTING_PASSWORD'] }
 before_filter :authenticate

 def authenticate
   authenticate_or_request_with_http_digest("Application") do |name|
     USERS[name]
   end
 end

 #####

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pups_controller.rb
class PupsController < ApplicationController
  before_action :set_pup, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pups = Pup.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)

  end

  def show
  end

  def new
    @pup = current_user.pups.build
  end

  def edit
  end

  def create
    @pup = current_user.pups.build(pup_params)
    if @pup.save
      redirect_to @pup, notice: 'Pup was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pup.update(pup_params)
      redirect_to @pup, notice: 'Pup was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pup.destroy
    redirect_to pups_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pup
      @pup = Pup.find(params[:id])
    end

    def correct_user
      @pup = current_user.pups.find_by(id: params[:id])
      redirect_to pups_path, notice: "Not authorized to edit this pup" if @pup.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pup_params
      params.require(:pup).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pups_helper.rb
module PupsHelper
end

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pupperesting", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
            <li>
              <%= link_to new_pup_path do %>
                <span class="glyphicon glyphicon-plus"></span> New Pup
              <% end %>
            </li>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon_paw.ico' %>
  <title>Pupperesting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render 'layouts/header' %>
  <div class="container">
  	<% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
  	<% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
    <h1>
    	<span class="woof"><%= link_to "Woof", "https://www.youtube.com/watch?v=cXSUQcQcxqY", alt: "Puppy barking", target: "_blank" %></span>
    	<span class="guau" target="_blank"><%= link_to "Guau", "https://www.youtube.com/watch?v=1PrRjMnaMX4", alt: "Perrito ladrando", target: "_blank" %></span>
    	<span class="wau"><%= link_to "Wau", "https://www.youtube.com/watch?v=PpBU3DhU_pQ", alt: "Welpe bellt", target: "_blank" %></span>
    </h1>
    
     <p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>  
</div>

app/views/pages/about.html.erb
<div class="jumbotron center">
	<span class="about"><h1>About us</h1>
	<p><span class="wauwau_about">We're puppies.</span></p></span>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
    <h1>Welcome to my app!</h1>
    <% if user_signed_in? %>
    	# do something
    <% else %>
     <p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>  
  <% end %>
</div>

app/views/pups/_form.html.erb
<%= form_for @pup, html: { multipart: true } do |f| %>
  <% if @pup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pup.errors.count, "error") %> prohibited this pup from being saved:</h2>

      <ul>
      <% @pup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pups/edit.html.erb
<div class="jumbotron center">
	<div class="pupdate">
		<h1>Pupdate Your Pup</h1>
	</div>

	<%= render 'form' %>

	<%= link_to 'Show', @pup %> |
	<%= link_to 'Back', pups_path %>

</div>

app/views/pups/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pups" class="transitions-enabled">
  <% @pups.each do |pup| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pup.image.url(:medium)), pup %>
      <div class="panel-body">
        <div class="user_post_descriptions">
          <%= pup.description %><br/>
          <strong><%= pup.user.name if pup.user %></strong>
        </div>
        <% if current_user && pup.user == current_user %>
          <div class="actions">
            <%= link_to edit_pup_path(pup) do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= link_to pup, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pups/new.html.erb
<div class="jumbotron center">
  <div class="new_pup">
		<h1>New pup</h1>
	</div>

	<%= render 'form' %>

	<%= link_to 'Back', pups_path %>
</div>

app/views/pups/show.html.erb
<%= link_to 'Back', pups_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pup.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pup.description %></p>
        <p><strong><%= @pup.user.name if @pup.user %></strong></p>

        <% if @pup.user == current_user %>
         <%= link_to 'Edit', edit_pup_path(@pup) %>
        <% end %>

      </div>
    </div>
  </div>
</div>